name: Cross-platform JAR Release with Launchers

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  package:
    name: Package Launchers
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Maven version from tag
        id: set-version
        run: mvn versions:set -DnewVersion=$VERSION

      - name: Build JAR
        run: mvn -B package --file pom.xml

      - name: Create Launcher
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            mkdir dist-linux
            cp costsplit*.jar dist-linux/costsplit.jar
            cat > dist-linux/run.sh <<'EOF'
          #!/bin/sh
          export COSTSPLIT_URI=https://costsplit-456211.oa.r.appspot.com
          exec /usr/bin/java -jar "costsplit.jar" "$@"
          EOF
            chmod +x dist-linux/run.sh
            tar -czf costsplit-linux.tar.gz -C dist-linux .
          elif [ "$RUNNER_OS" = "Windows" ]; then
            mkdir dist-windows
            cp costsplit*.jar dist-windows/costsplit.jar
            echo @echo off > dist-windows/run.bat
            echo set COSTSPLIT_URI=https://costsplit-456211.oa.r.appspot.com >> dist-windows/run.bat
            echo start javaw -jar "costsplit.jar" %%* >> dist-windows/run.bat
            powershell Compress-Archive -Path dist-windows -DestinationPath costsplit-windows.zip
          fi
        shell: bash

      - name: Upload Platform Package
        uses: softprops/action-gh-release@v2
        with:
          files: |
            costsplit-linux.tar.gz
            costsplit-windows.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'windows')
